print("What is your name?")
name = input()
print("Hi " + name + "!")
print("How many sisters do you have?")
sisters = input()
print("Very nice, " + name + "!")
print("How many brothers do you have?")
brothers = input()
print("Superb, " + name + "!")
print("How many dogs do you have?")
dogs = input()
print("Thank you for answering, " + name + "!" " We know that you have " + brothers + " brothers, " + sisters + " sisters, " + "and " + dogs + " dogs!")